micronaut:
  application:
    name: openapiPoc
  # liberar acesso do yaml gerado via url
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger/swagger
        mapping: /swagger/**
      # libera acesso ao swagger-ui
      swagger-ui:
        paths: classpath:META-INF/swagger/swagger/views/swagger-ui/
        mapping: /swagger-ui/**